version: "3.10"
services:
    fastapi:
        build:
            context: backend
            dockerfile: Dockerfile.dev
        command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on:
            - db
    db:
        image: postgres
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
    react-app:
        build:
            context: react-app
            dockerfile: Dockerfile.dev
        # command: sh -c "npm rebuild esbuild && yarn dev"
        working_dir: /app
        volumes:
            - ./react-app:/app
        ports:
            - "5173:5173"
        environment:
            HOST_OS: ${OS}
            NODE_ENV: development
            HOST: "0.0.0.0"
            PUBLIC_URL: http://localhost:5173
            tty: true
            react-app: ${react-app}
